
adeept_rpi_pro:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


  # Position Controller
  arm_b_l1_joint_position_controller:
    #type: effort_controllers/JointPositionController
    type: position_controllers/JointPositionController
    joint: arm_b_l1_joint
    pid: { p: 100.0, i: 0.01, d: 10.0}
